pub mod user_handlers;
pub mod auth_handlers;
pub mod health_handlers;
pub mod artwork_handlers;
pub mod upload_handler;
pub mod cart_handlers;
pub mod order_handlers;
pub mod buyer_handlers;
pub mod artist_handlers;
